### ISSUE TITLE
Installation error in rancher 1.6.21

### ISSUE THREAD

**Issue by dpadron** [PacificCommunity/rancher-catalogue#1]
Hello,
I try to install geonode through the catagolo and the following error is generated:
Error (Existing secret admin_username not found)
Thanks for your attention
![error_geonode_rancher](https://user-images.githubusercontent.com/7094961/45743043-907b8680-bbfb-11e8-9aa7-99d24fe56af5.jpg)

**Comment by olivierdalang** [comment]
You missed the small notes at the bottom (I agree it should be in the readme) :

> For this stack to work, you need to add the Rancher Secrets service from the catalog. See http://rancher.com/docs/rancher/v1.4/en/cattle/secrets/#enabling-secrets-in-containers for more informations

And the create the following secrets :
- admin_username
- admin_password
- aws_access_key
- aws_secret_key

Also I didn't push updates for some time on this setup. If using docker-compose from the SPCgeonode directly is an option, I recommend sticking to that for now.

**Comment by dpadron** [comment]
Thanks Oliver for our Answer I'm going to try it


*----------------------------------*
*Diego José Padrón*
@diegojpadron
